apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-sechub.fullname" . }}
  labels:
    {{- include "api-sechub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-sechub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-sechub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api-sechub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- /* Volúmenes: añadimos el ConfigMap del main.py si está habilitado */ -}}
      {{- if .Values.mainPyConfig.enabled }}
      volumes:
        - name: {{ include "api-sechub.fullname" . }}-main
          configMap:
            name: {{ include "api-sechub.fullname" . }}-main
            items:
              - key: main.py
                path: main.py
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: sechubURL
              value: "{{ .Values.envVars.sechubURL }}"
            - name: sechubToken
              value: "{{ .Values.envVars.sechubToken }}"
            - name: product
              value: "{{ .Values.envVars.product }}"
            - name: productName
              value: "{{ .Values.envVars.productName }}"

          {{- /* Montamos el main.py desde el ConfigMap si está habilitado */ -}}
          {{- if .Values.mainPyConfig.enabled }}
          volumeMounts:
            - name: {{ include "api-sechub.fullname" . }}-main
              mountPath: /app/main.py
              subPath: main.py
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
